export default [
  {
    id: 0,
    title: "Deliver iPhone 14 Pro Max to USER_ID",
    allDay: true,
    start: new Date(),
    end: new Date(),
  },
  {
    id: 1,
    title: "Deliver iPhone 14 Pro Max to USER_ID",
    allDay: true,
    start: new Date(),
    end: new Date(),
  },
  {
    id: 2,
    title: "Deliver iPhone 14 Pro Max to USER_ID",
    allDay: true,
    start: new Date(),
    end: new Date(),
  },
  {
    id: 3,
    title: "Deliver iPhone 14 Pro Max to USER_ID",
    allDay: true,
    start: new Date(),
    end: new Date(),
  },
  {
    id: 4,
    title: "Deliver iPhone 14 Pro Max to USER_ID",
    allDay: true,
    start: new Date(),
    end: new Date(),
  },
  {
    id: 5,
    title: "Deliver iPhone 14 Pro Max to USER_ID",
    allDay: true,
    start: new Date(),
    end: new Date(),
  },
  {
    id: 6,
    title: "Deliver iPhone 14 Pro Max to USER_ID",
    allDay: true,
    start: new Date(),
    end: new Date(),
  },
  {
    id: 7,
    title: "Deliver iPhone 14 Pro Max to USER_ID",
    allDay: true,
    start: new Date(),
    end: new Date(),
  },
  {
    id: 9,
    title: "Deliver iPhone 14 Pro Max to USER_ID",
    allDay: true,
    start: new Date(),
    end: new Date(),
  },
  {
    id: 10,
    title: "Deliver iPhone 14 Pro Max to USER_ID",
    allDay: true,
    start: new Date(),
    end: new Date(),
  },
  {
    id: 11,
    title: "Deliver iPhone 14 Pro Max to USER_ID",
    allDay: true,
    start: new Date(),
    end: new Date(),
  },
  {
    id: 12,
    title: "Deliver iPhone 14 Pro Max to USER_ID",
    allDay: true,
    start: new Date(),
    end: new Date(),
  },
  {
    id: 13,
    title: "Deliver iPhone 14 Pro Max to USER_ID",
    allDay: true,
    start: new Date(),
    end: new Date(),
  },
  {
    id: 14,
    title: "Deliver iPhone 14 Pro Max to USER_ID",
    allDay: true,
    start: new Date(),
    end: new Date(),
  },
  {
    id: 15,
    title: "Deliver iPhone 14 Pro Max to USER_ID",
    allDay: true,
    start: new Date(),
    end: new Date(),
  },
  {
    id: 16,
    title: "Deliver iPhone 14 Pro Max to USER_ID",
    allDay: true,
    start: new Date(),
    end: new Date(),
  },
];
  