import Head from 'next/head';

const Login = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container py-12 md:py-16">
          <h1 className="text-3xl font-bold">Login</h1>
        </div>
      </main>
    </div>
  );
};

export default Login;
